### ISSUE TITLE
The specified child already has a parent (Android)

### ISSUE THREAD

**Issue by bachras** [moayadnajd/nativescript-filter-select#37]
Hi,

Thanks again for brilliant plugin. Sometimes I get the error below after tapping on filterselect. Here is my code below. Do you have any ideas what could be wrong? Thanks

```
             <FilterSelect
                id="languageSelect" 
                height="100%"
                render="drop"
                [items]="languages"     
                (change)="selectLanguage($event)"
                hint="Language" 
                modal_title="Language" 
                primary_key="lang"
                search_param="lang" 
                [selected]="selectedLanguage">  
             </FilterSelect>
```
```
System.err: com.tns.NativeScriptException: 
System.err: Calling js method onCreateDialog failed
System.err: Error: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
System.err:     android.view.ViewGroup.addViewInner(ViewGroup.java:3936)
System.err:     android.view.ViewGroup.addView(ViewGroup.java:3786)
System.err:     android.view.ViewGroup.addView(ViewGroup.java:3758)
System.err:     com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:407)
System.err:     android.app.Dialog.setContentView(Dialog.java:513)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     com.tns.gen.android.app.DialogFragment_frnal_ts_helpers_l58_c38__DialogFragmentImpl.onCreateDialog(DialogFragment_frnal_ts_helpers_l58_c38__DialogFragmentImpl.java:12)
System.err:     android.app.DialogFragment.getLayoutInflater(DialogFragment.java:398)
System.err:     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
System.err:     android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
System.err:     android.app.BackStackRecord.run(BackStackRecord.java:834)
System.err:     android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
System.err:     android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
System.err:     android.os.Handler.handleCallback(Handler.java:739)
System.err:     android.os.Handler.dispatchMessage(Handler.java:95)
System.err:     android.os.Looper.loop(Looper.java:135)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5254)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     java.lang.reflect.Method.invoke(Method.java:372)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
System.err: File: "file:///data/data/org.nativescript.app1/files/app/tns_modules/tns-core-modules/ui/page/page.js, line: 42, column: 19
System.err: StackTrace: 
System.err: 	Frame: function:'DialogFragmentImpl.onCreateDialog', file:'file:///data/data/org.nativescript.app1/files/app/tns_modules/tns-core-modules/ui/page/page.js', line: 42, column: 20
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err: 	at com.tns.gen.android.app.DialogFragment_frnal_ts_helpers_l58_c38__DialogFragmentImpl.onCreateDialog(DialogFragment_frnal_ts_helpers_l58_c38__DialogFragmentImpl.java:12)
System.err: 	at android.app.DialogFragment.getLayoutInflater(DialogFragment.java:398)
System.err: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:894)
System.err: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
System.err: 	at android.app.BackStackRecord.run(BackStackRecord.java:834)
System.err: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
System.err: 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:447)
System.err: 	at android.os.Handler.handleCallback(Handler.java:739)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: 	at android.os.Looper.loop(Looper.java:135)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5254)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at java.lang.reflect.Method.invoke(Method.java:372)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
System.err: Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
System.err: 	at android.view.ViewGroup.addViewInner(ViewGroup.java:3936)
System.err: 	at android.view.ViewGroup.addView(ViewGroup.java:3786)
System.err: 	at android.view.ViewGroup.addView(ViewGroup.java:3758)
System.err: 	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:407)
System.err: 	at android.app.Dialog.setContentView(Dialog.java:513)
System.err: 	... 21 more
```

**Comment by moayadnajd** [comment]
hi can you make a example on https://play.nativescript.org/  so i can check if faster sorry for the delay

**Comment by moayadnajd** [comment]
@bachras did you solve this ? please let me know

**Comment by leocrawf** [comment]
I am using NS core, so no angular here. However, I have had similar issues when I have an unreferenced function attached to an event listener on the FilterSelect XML. For example, if there is 
    <FilterSelect
    selected="someFunction"
    .......
and someFunction does not exist, I would get that exception. Hopefully, this info can point you in the right direction.

**Comment by moayadnajd** [comment]
@leocrawf so you have this issue also ?? @bachras i can't reproduce it can you help
