### ISSUE TITLE
Angular with webpack

### ISSUE THREAD

**Issue by bachras** [moayadnajd/nativescript-filter-select#43]
Hi,

Thanks again for brilliant plugin. I saw the issue which you have solved for VanillaJS in https://github.com/moayadnajd/nativescript-filter-select/issues/18. Could you please provide working example with Angular as well? Thanks in advance 

Here is the error I am currently having:
````
System.err: com.tns.NativeScriptException: 
System.err: Calling js method getView failed
System.err: 
System.err: Error: Parsing XML at 1:1
System.err:  > Module 'ui/label' not found for element 'Label'.
System.err:    > t is not a function
System.err: File: "<embedded>, line: 36, column: 705303
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'oe', file:'<embedded>', line: 36, column: 893733
System.err: 	Frame: function:'t', file:'<embedded>', line: 36, column: 655474
System.err: 	Frame: function:'o', file:'<embedded>', line: 36, column: 705461
System.err: 	Frame: function:'', file:'<embedded>', line: 36, column: 705312
System.err: 	Frame: function:'', file:'<embedded>', line: 36, column: 1071548
System.err: 	Frame: function:'n.parse', file:'<embedded>', line: 36, column: 1080476
System.err: 	Frame: function:'e.parse', file:'<embedded>', line: 36, column: 1072580
System.err: 	Frame: function:'t.parse', file:'<embedded>', line: 36, column: 705394
System.err: 	Frame: function:'m', file:'<embedded>', line: 36, column: 703076
System.err: 	Frame: function:'y', file:'<embedded>', line: 36, column: 702577
System.err: 	Frame: function:'createView', file:'<embedded>', line: 36, column: 932683
System.err: 	Frame: function:'ListViewAdapter.getView', file:'<embedded>', line: 36, column: 931133
System.err: 
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err: 	at com.tns.gen.android.widget.BaseAdapter_frnal_ts_helpers_l58_c38__ListViewAdapter.getView(BaseAdapter_frnal_ts_helpers_l58_c38__ListViewAdapter.java:47)
System.err: 	at android.widget.AbsListView.obtainView(AbsListView.java:3189)
System.err: 	at android.widget.ListView.makeAndAddView(ListView.java:2197)
System.err: 	at android.widget.ListView.fillDown(ListView.java:824)
System.err: 	at android.widget.ListView.fillFromTop(ListView.java:885)
System.err: 	at android.widget.ListView.layoutChildren(ListView.java:1952)
System.err: 	at android.widget.AbsListView.onLayout(AbsListView.java:2961)
System.err: 	at android.view.View.layout(View.java:20822)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6401)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.StackLayout.layoutVertical(StackLayout.java:169)
System.err: 	at org.nativescript.widgets.StackLayout.onLayout(StackLayout.java:123)
System.err: 	at android.view.View.layout(View.java:20822)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6401)
System.err: 	at org.nativescript.widgets.CommonLayoutParams.layoutChild(CommonLayoutParams.java:222)
System.err: 	at org.nativescript.widgets.GridLayout.onLayout(GridLayout.java:353)
System.err: 	at android.view.View.layout(View.java:20822)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6401)
System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err: 	at android.view.View.layout(View.java:20822)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6401)
System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err: 	at android.view.View.layout(View.java:20822)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6401)
System.err: 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
System.err: 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
System.err: 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:944)
System.err: 	at android.view.View.layout(View.java:20822)
System.err: 	at android.view.ViewGroup.layout(ViewGroup.java:6401)
System.err: 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2907)
System.err: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2594)
System.err: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1738)
System.err: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7745)
System.err: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
System.err: 	at android.view.Choreographer.doCallbacks(Choreographer.java:723)
System.err: 	at android.view.Choreographer.doFrame(Choreographer.java:658)
System.err: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
System.err: 	at android.os.Handler.handleCallback(Handler.java:789)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:98)
System.err: 	at android.os.Looper.loop(Looper.java:164)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6938)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)


````

**Comment by anuragd7** [comment]
@bachras - I was able to get ti to wrk by including the following in the component ts file.

```
elementRegistryModule.registerElement("FilterSelect", () => require("nativescript-filter-select").FilterSelect);
// next 4 lines to enable filter select to work with webpack
require('globals');
global.registerModule('ui/layouts/grid-layout', () => require('tns-core-modules/ui/layouts/grid-layout'));
global.registerModule('ui/label', () => require('tns-core-modules/ui/label'));
global.registerModule('nativescript-web-image-cache', () => require('nativescript-web-image-cache'))
```;

Hope it works for you.

**Comment by bachras** [comment]
@anuragd7 Thank you very much. It worked like a charm. You are a life saver!
